version: '3'

services:
  wiki:
    container_name: minecolonies_wiki
    image: docker.minecolonies.com/wiki:latest
    restart: unless-stopped
    expose:
      - 4000
    environment:
      - VIRTUAL_HOST=wiki.minecolonies.com, www.wiki.minecolonies.com, minecolonieswiki.orionminecraft.com, www.minecolonieswiki.orionminecraft.com
      - VIRTUAL_PROTO=http
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=wiki.minecolonies.com, www.wiki.minecolonies.com, minecolonieswiki.orionminecraft.com, www.minecolonieswiki.orionminecraft.com
      - LETSENCRYPT_EMAIL=marcf1@hotmail.com
      - JEKYLL_GITHUB_TOKEN=${GITHUB_TOKEN}

networks:
  default:
    external:
      name: webproxy
