version: '3.8'

services:
  jekyll-host:
    image: container.ldtteam.com/ldtteam/minecolonies/wiki:latest
    environment:
      - JEKYLL_GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.system==production
          - node.labels.type==worker
          - node.labels.web==true
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.wiki-minecolonies-http.rule=Host(`wiki.minecolonies.ldtteam.com`)
        - traefik.http.routers.wiki-minecolonies-http.entrypoints=http
        - traefik.http.routers.wiki-minecolonies-http.middlewares=https-redirect
        - traefik.http.routers.wiki-minecolonies-https.rule=Host(`wiki.minecolonies.ldtteam.com`)
        - traefik.http.routers.wiki-minecolonies-https.entrypoints=https
        - traefik.http.routers.wiki-minecolonies-https.tls=true
        - traefik.http.routers.wiki-minecolonies-https.service=wiki-minecolonies
        - traefik.http.routers.wiki-minecolonies-https.tls.certresolver=le
        - traefik.http.services.wiki-minecolonies.loadbalancer.server.port=4000
        - traefik.http.services.my-service.loadBalancer.sticky.cookie.name=ldtteam-routing_minecolonies-wiki
        - traefik.http.services.my-service.loadBalancer.sticky.cookie.secure=true
        - traefik.http.services.my-service.loadBalancer.sticky.cookie.httpOnly=true
        - traefik.http.services.my-service.loadBalancer.sticky.cookie.sameSite=none


networks:
  traefik-public:
    external: true
